spring:
  application:
    name: api-monitoring-dashboard
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: ${PORT:8080}
  error:
    include-message: always
jwt:
  secret: ${JWT_SECRET:change-this-very-secret-key}
  expirationSeconds: 86400
management:
  endpoints:
    web:
      exposure:
        include: health,info
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  allowed-methods: GET,POST,DELETE,PUT,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
